### PR TITLE
fix(ci/lint): fix failing lint checks

### LINKED ISSUE #203: Fix Golang Lint issues in MeshKit
Please add appropriate labels and request review.

Lint failures need attention.

_Originally posted by @leecalcote in https://github.com/meshery/meshkit/pull/201#pullrequestreview-1065619309_

### PR DESCRIPTION
**Pull request by pk-218**
Signed-off-by: pk-218 <53428217+pk-218@users.noreply.github.com>

**Description**

This PR fixes #203 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by theBeginner86** [comment]
Thanks, @pk-218 for this PR.

This doesn't seem to entirely take care of them. Will you please see the lint check failures ([here](https://github.com/meshery/meshkit/runs/8163486896?check_suite_focus=true#step:4:79))?

**Comment by pk-218** [comment]
That's strange. When I used [act](https://github.com/nektos/act) to run the CI locally, I found no issues.
Will look into it

**Comment by leecalcote** [comment]
Maybe it has improved. I never really had any luck with act.

**Comment by pk-218** [comment]
If not `act`, how do you run GitHub Actions locally?

**Comment by theBeginner86** [comment]
> If not `act`, how do you run GitHub Actions locally?

I personally use `golangci-lint`, a command line tool for lint testing Golang code (check more [here](https://golangci-lint.run)). One of the reason I use it is because it the exact same tool which we use in our testing scripts so it would do the exact same level of testing locally as done in the CI environment of layer5 projects.

File: utils/walker/git.go [hunk 1]
```diff
@@ -172,10 +172,19 @@ func clonewalk(g *Git) error {
...
 	}
+	files := make([]fs.FileInfo, 0, len(entries))
+	for _, entry := range entries {
+		file, err := entry.Info()
+		if err != nil {
+			return err
+		}
+		files = append(files, file)
+	}
+
```
Comment (theBeginner86) [inline utils/walker/git.go:187]: @pk-218 what's the need for this? Is this part of lint failures? 🤔

**Comment by pk-218** [comment]
Same, that's how I can catch and fix these failing lint checks xD 
Was wondering what else Lee uses apart from `act` to run other GitHub Actions locally

File: utils/walker/git.go (hunk 1 above)
Comment (pk-218) [reply utils/walker/git.go:187]: The lint checks were failing here since `ioutil.ReadDir` is deprecated

As per the [documentation](https://pkg.go.dev/io/ioutil#ReadDir), the replacement is `os.ReadDir` but there is a change in the method return value. Hence, to accommodate the changes, I had to add this code.

Comment (theBeginner86) [reply utils/walker/git.go:187]: Ohh I see.

**Review by theBeginner86 — APPROVED** [review]
LGTM
Thanks @pk-218 for looking through this.
