### PR TITLE
fix [catalog]: handle time.TIme & nil createdAt time in ArtifactHub package buiilder

### LINKED ISSUE #556: Ensure Artifact Hub builder typecasts timestamps
Thanks for this @ctcarrier . 

Ideally, we would want this to be handled within the `BuildArtifactHubPkg` in Meshkit. The `BuildArtifactHubPkg` function should take `time` type as a parameter rather than `string`. And inside the `BuildArtifactHubPkg` function, we would try to parse it to RFC3339.

_Originally posted by @humblenginr in https://github.com/meshery/meshery/pull/11595#discussion_r1712306508_

### PR DESCRIPTION
**Pull request by ShashaankS**
**Description**
Now the BuilderArtifactHubPkg function accepts *time.Time (i.e a pointer) instead of string.
The function now the handles the nil case also.

This PR fixes #556 

**Note for Reviewers**
Original functionality is maintained, adding retention for golang format. 

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

File: utils/catalog/package.go [hunk 1]
```diff
@@ -2,12 +2,22 @@ package catalog
...
 	"strings"
+	"time"
+
+	"github.com/meshery/meshkit/models/catalog/v1alpha1"
 )
 
-func BuildArtifactHubPkg(name, downloadURL, user, version, createdAt string, catalogData *v1alpha1.CatalogData) *ArtifactHubMetadata {
+func BuildArtifactHubPkg(name, downloadURL, user, version string, createdAt *time.Time, catalogData *v1alpha1.CatalogData) *ArtifactHubMetadata {
+	
+	var createdAtStr time.Time
```
Comment (n2h9) [inline utils/catalog/package.go]: I think the name is slightly misleading, as the variable contains not a string but time.Time, also there are some extra spaces (or tabs)  in the line.

Comment (ShashaankS) [reply utils/catalog/package.go]: I will renamed it to `createdTime`, for the convenience.

File: utils/catalog/package.go [hunk 2]
```diff
@@ -2,12 +2,21 @@ package catalog
...
 	"regexp"
 	"strings"
+	"time"
+
+	"github.com/meshery/meshkit/models/catalog/v1alpha1"
 )
 
-func BuildArtifactHubPkg(name, downloadURL, user, version, createdAt string, catalogData *v1alpha1.CatalogData) *ArtifactHubMetadata {
+func BuildArtifactHubPkg(name, downloadURL, user, version string, createdAt *time.Time, catalogData *v1alpha1.CatalogData) *ArtifactHubMetadata {
+	var createdTime time.Time
```
Comment (n2h9) [inline utils/catalog/package.go:13]: Could you please remove extra tabs (or spaces) ?

f.e. by running
```
gofmt -w utils/catalog/package.go
```

:innocent:

Comment (ShashaankS) [reply utils/catalog/package.go:13]: Did formatting using gofmt pkg. 😅
Hope this works.

Comment (n2h9) [reply utils/catalog/package.go:13]: Lol kek :smile: 

it was actually not about moving to the left line 13 but rather to the right line 14 block :rofl: 

anyway. . . 
it should be on the same level as line 20.

Thank you for handling this :white_check_mark:  :bowing_woman:

**Review by n2h9 — APPROVED** [review]
